name: ci
on: push
jobs:
  magic-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:static
        env:
          # assume that all backend calls to "/todos" are pre-recorded
          # in the cypress/magic-backend folder
          # and on CI the API backend should be in playback mode
          # and completely stubbed
          CYPRESS_magic_backend_mode: playback
